# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxShop = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxShop.setGeometry(QtCore.QRect(890, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxShop.setFont(font)
        self.comboBoxShop.setCurrentText("")
        self.comboBoxShop.setObjectName("comboBoxShop")
        self.comboBoxItem = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxItem.setGeometry(QtCore.QRect(10, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxItem.setFont(font)
        self.comboBoxItem.setCurrentText("")
        self.comboBoxItem.setObjectName("comboBoxItem")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(720, 20, 111, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(990, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEditUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUrl.setGeometry(QtCore.QRect(700, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEditUrl.setFont(font)
        self.lineEditUrl.setObjectName("lineEditUrl")
        self.comboBoxStyle = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxStyle.setGeometry(QtCore.QRect(180, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxStyle.setFont(font)
        self.comboBoxStyle.setCurrentText("")
        self.comboBoxStyle.setObjectName("comboBoxStyle")
        self.comboBoxGender = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxGender.setGeometry(QtCore.QRect(350, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxGender.setFont(font)
        self.comboBoxGender.setObjectName("comboBoxGender")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.comboBoxWeight = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxWeight.setGeometry(QtCore.QRect(450, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxWeight.setFont(font)
        self.comboBoxWeight.setObjectName("comboBoxWeight")
        self.comboBoxWeight.addItem("")
        self.comboBoxWeight.addItem("")
        self.comboBoxWeight.addItem("")
        self.comboBoxWeight.addItem("")
        self.lineEditStyleNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditStyleNumber.setGeometry(QtCore.QRect(620, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEditStyleNumber.setFont(font)
        self.lineEditStyleNumber.setObjectName("lineEditStyleNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 20, 111, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ссылка на одежду"))
        self.pushButton.setText(_translate("MainWindow", "Add item"))
        self.comboBoxGender.setCurrentText(_translate("MainWindow", "Men"))
        self.comboBoxGender.setItemText(0, _translate("MainWindow", "Men"))
        self.comboBoxGender.setItemText(1, _translate("MainWindow", "Women"))
        self.comboBoxWeight.setCurrentText(_translate("MainWindow", "NormalBodyWeight"))
        self.comboBoxWeight.setItemText(0, _translate("MainWindow", "NormalBodyWeight"))
        self.comboBoxWeight.setItemText(1, _translate("MainWindow", "BodyMassDeficiency"))
        self.comboBoxWeight.setItemText(2, _translate("MainWindow", "Overweight"))
        self.comboBoxWeight.setItemText(3, _translate("MainWindow", "Underweight"))
        self.label_2.setText(_translate("MainWindow", "Номер стиля"))


